### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getSelectedText' of undefined

### ISSUE THREAD

**Issue by jbc913** [manngo/atom-web-tools#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Home
**Thrown From**: [web-developer-tools](https://github.com/manngo/atom-web-tools) package 0.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getSelectedText' of undefined

```
At C:\Users\Justin\.atom\packages\web-developer-tools\lib\web-tools.js:184

TypeError: Cannot read property 'getSelectedText' of undefined
    at Object.init (/packages/web-developer-tools/lib/web-tools.js:184:28)
    at Object.insert (/packages/web-developer-tools/lib/web-tools.js:474:31)
    at HTMLElement.webToolsHtmlInsert (/packages/web-developer-tools/lib/web-tools.js:147:43)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:352215)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:350690)
    at AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:1:833360)
    at EventEmitter.t (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:1:841331)
    at EventEmitter.emit (events.js:223:5)
    at Object.onMessage (electron/js2c/renderer_init.js:115:818)
```

### Commands

```
  7x -1:31.5.0 github:selectbox-backspace (input.)
     -0:23.3.0 hydrogen:run (div.github-StagingView.unstaged-changes-focused)
     -0:14.3.0 snippets:available (div.github-StagingView.unstaged-changes-focused)
     -0:08.2.0 web-tools:html:insert (div.github-StagingView.unstaged-changes-focused)
```

### Non-Core Packages

```
atom-clock 0.1.18 
atom-ide-base 2.6.0 
atom-ide-console 0.0.2 
atom-ide-datatip 0.24.1 
atom-ide-debugger 0.0.3 
atom-ide-definitions 0.4.1 
atom-ide-hyperclick 1.0.10 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 2.3.4 
atom-ide-signature-help 0.15.3 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
busy-signal 2.0.1 
Hydrogen 2.16.2 
intentions 1.1.5 
kite 0.205.0 
linter 3.3.1 
linter-ui-default 3.3.1 
teletype 0.13.4 
web-developer-tools 0.4.0 
```

**Comment by jbc913** [comment]
llllkpmo
